### ISSUE TITLE
Cannot load Java class org.slf4j.MDC

### ISSUE THREAD

**Issue by LeifWarner** [at-point/loggr#2]
Any use of this with SL4J seems to fail with:
`NameError: cannot load Java class org.slf4j.MDC`
e.g. running `Loggr::SLF4J::Logger.new`

**Comment by IDEA-Fang** [comment]
> Loggr makes the assumption that SLF4J is already on the classpath, if this is not the case you can load the bundled slf4j & logback jars using
> 
> ```
> require 'loggr/slf4j/jars'
> Loggr::SLF4J::Jars.require_slf4j_jars!
> ```
> 
> Hope this helps, if not could you give me some details about jruby version and how you're starting it?

how can i set this setting in my config，when use a maven project
like:
            <dependency>
                <groupId>org.slf4j</groupId>
                <artifactId>slf4j-log4j12</artifactId>
                <version>1.7.2</version>
            </dependency>
